#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MemeticaMeDeLaCerda.Resource", IsApplication=true)]

namespace MemeticaMeDeLaCerda
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ContactsMenu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int MissingContact = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070011
			public const int BTRegistrar = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int ContactImage = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int ContactName = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int ContactsList = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int ContactsListView = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int ETNombreUsuario = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int ETNumeroTelefono = 2131165200;
			
			// aapt resource value: 0x7f070000
			public const int LinearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int TVMemeticame = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int TVNombreUsuario = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int TVNumeroTelefono = 2131165199;
			
			// aapt resource value: 0x7f070003
			public const int buttonAddToDo = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int buttonSend = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int checkToDoItem = 2131165202;
			
			// aapt resource value: 0x7f070006
			public const int editText1 = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int listViewToDo = 2131165188;
			
			// aapt resource value: 0x7f070013
			public const int menu_refresh = 2131165203;
			
			// aapt resource value: 0x7f070005
			public const int tableRow1 = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int textNewToDo = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int textViewTitle = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_To_Do = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Chat = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ContactListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ContactsList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Init = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Row_List_To_Do = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int add_button_text = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int add_textbox_hint = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int checkbox_text = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int menu_refresh = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int mobile_services = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
